name: "OpenAPI Diff Action"
author: "Dmitry Vasiliev"
description: "A GitHub Action to identify differences between OpenAPI specifications. It uses OpenAPITools/openapi-diff."
branding:
  icon: 'check-square'
  color: 'blue'

inputs:
  old-spec:
    description: "Old specification filename"
    required: true
  new-spec:
    description: "New specification filename"
    required: true

outputs:
  state:
    description: "Output Diff Report"
    value: ${{steps.output_markdown_report.outputs.content}}

runs:
  using: composite
  steps:
    - name: "Run openapi-diff tool"
      run: |
        docker run -v "$(pwd):/specs" --rm openapitools/openapi-diff:2.0.1 \
          /specs/${{inputs.old-spec}} \
          /specs/${{inputs.new-spec}} \
          --log ERROR \
          --markdown /specs/report.md \
      shell: bash
    - name: "Read Markdown report"
      id: output_markdown_report
      uses: juliangruber/read-file-action@v1
      with:
        path: /specs/report.md

